name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: centos

    name: PHP

    steps:
      - name: '检查代码'
        uses: https://github.com/actions/checkout@v3

      - name: '安装PHP'
        uses: XiaoLFeng/setup-php@v2
        with:
          coverage: none
          tools: phpmd

      - name: '运行PHPMD'
        run: phpmd ./ text codesize
        continue-on-error: true
